### ISSUE TITLE
MLH Banner

### ISSUE THREAD

**Issue by adriandarian** [HackMerced/HackMerced-V#9]
**Describe the bug**
When clicking on the MLH banner the URL gets messed up and does not redirect properly

**To Reproduce**
1. Go to `hackmerced.io`
2. Click on `MLH Banner`
3. Look at URL

**Expected behavior**
Should redirect to https://mlh.io/seasons/na-2020/events

**Screenshots**
![image](https://user-images.githubusercontent.com/23567187/73130955-40fb5680-3fb7-11ea-982d-15694196082d.png)

**Desktop (please complete the following information):**
 - OS: [*]
 - Browser [*]
 - Version [*]

**Smartphone (please complete the following information):**
 - Device: [*]
 - OS: [*]
 - Browser [*]
 - Version [*]

**Comment by shiv248** [comment]
fixed in PR #8
